# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RodKom' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RodKom


  #infrastructure
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'

  #data
  pod 'RxCoreData'


  #transform
  pod 'Gloss', '0.7.4'

end
